const interests = [
    'Python',
    'JavaScript',
    'Java',
    'C++',
    'C#',
    'PHP',
    'Ruby',
    'Swift',
    'Go',
    'TypeScript',
    'HTML/CSS',
    'SQL',
    'MongoDB',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Express.js',
    'Django',
    'Flask',
    'Spring Boot',
    'ASP.NET',
    'Rust',
    'Kotlin',
    'Scala',
    'Perl',
    'Bash/Shell Scripting',
    'Lua',
    'Assembly Language',
    'Clojure',
    'Groovy',
    'Objective-C',
    'MATLAB',
    'R',
    'F#',
    'Dart',
    'Julia',
    'Haskell',
    'Solidity',
    'Ethereum',
    'WebAssembly (Wasm)',
    'TensorFlow',
    'PyTorch',
    'Keras',
    'OpenCV',
    'Pandas',
    'NumPy',
    'GraphQL',
    'Apache Kafka',
    'Redis',
    'Elasticsearch',
    'Docker',
    'Kubernetes',
    'AWS (Amazon Web Services)',
    'Microsoft Azure',
    'Google Cloud Platform (GCP)',
    'Serverless Computing',
    'Microservices Architecture',
    'DevOps',
    'Continuous Integration / Continuous Deployment (CI/CD)',
    'Agile Methodologies',
    'Test-Driven Development (TDD)',
    'Behavior-Driven Development (BDD)',
    'Git',
    'Subversion (SVN)',
    'Mercurial (Hg)',
    'Jenkins',
    'CircleCI',
    'Travis CI',
    'Jira',
    'Confluence',
    'Slack (for Development Teams)',
    'Agile Project Management Tools',
    'Scrum',
    'Kanban',
    'Pair Programming',
    'Code Review',
    'Cryptography',
    'Cybersecurity',
    'Penetration Testing',
    'Web Development',
    'Mobile App Development',
    'Game Development',
    'Augmented Reality (AR)',
    'Virtual Reality (VR)',
    'Blockchain Development',
    'Cryptocurrency',
    'Decentralized Finance (DeFi)',
    'Artificial Intelligence (AI)',
    'Machine Learning',
    'Natural Language Processing (NLP)',
    'Computer Vision',
    'Big Data',
    'Data Engineering',
    'Data Analytics',
    'Data Visualization',
    'Business Intelligence (BI)',
    'Internet of Things (IoT)',
    'Embedded Systems',
    'Quantum Computing'
];

const detailedInterests = [
    { word: 'Python', definition: 'Python is a high-level, interpreted programming language known for its readability and simplicity, used in web development, data analysis, artificial intelligence, scientific computing, and more.' },
    { word: 'JavaScript', definition: 'JavaScript is a versatile, high-level programming language primarily used for creating interactive effects within web browsers. It is a core technology of the World Wide Web.' },
    { word: 'Java', definition: 'Java is a high-level, class-based, object-oriented programming language designed to have as few implementation dependencies as possible. It is used in web development, Android apps, and enterprise software.' },
    { word: 'C++', definition: 'C++ is a general-purpose programming language that extends C with object-oriented features. It is used in system/software development, game development, and high-performance applications.' },
    { word: 'C#', definition: 'C# is a modern, object-oriented programming language developed by Microsoft. It is used primarily for developing applications on the .NET framework, including web, desktop, and mobile applications.' },
    { word: 'PHP', definition: 'PHP is a server-side scripting language designed primarily for web development but also used as a general-purpose language. It is commonly used to create dynamic web pages.' },
    { word: 'Ruby', definition: 'Ruby is a high-level, interpreted programming language known for its simplicity and productivity. It is often used in web development, particularly with the Ruby on Rails framework.' },
    { word: 'Swift', definition: 'Swift is a powerful, open-source programming language developed by Apple for building iOS, macOS, watchOS, and tvOS applications. It is designed for performance and safety.' },
    { word: 'Go', definition: 'Go, also known as Golang, is an open-source programming language developed by Google. It is known for its simplicity, efficiency, and strong concurrency support, making it suitable for scalable systems.' },
    { word: 'TypeScript', definition: 'TypeScript is a statically typed superset of JavaScript developed by Microsoft. It adds optional types to JavaScript and is compiled to plain JavaScript for execution.' },
    { word: 'HTML/CSS', definition: 'HTML (HyperText Markup Language) is the standard language for creating web pages and web applications, while CSS (Cascading Style Sheets) is used to style and layout HTML elements.' },
    { word: 'SQL', definition: 'SQL (Structured Query Language) is a domain-specific language used in programming and managing relational databases. It is used for querying and manipulating data.' },
    { word: 'MongoDB', definition: 'MongoDB is a NoSQL database that uses a document-oriented data model. It is designed for scalability and flexibility, allowing for the storage of complex data structures.' },
    { word: 'React', definition: 'React is a JavaScript library developed by Facebook for building user interfaces, particularly single-page applications with a component-based architecture.' },
    { word: 'Angular', definition: 'Angular is a TypeScript-based open-source web application framework developed by Google. It is used for building dynamic web applications and provides a comprehensive solution for frontend development.' },
    { word: 'Vue.js', definition: 'Vue.js is a progressive JavaScript framework for building user interfaces. It is designed to be incrementally adoptable and focuses on the view layer.' },
    { word: 'Node.js', definition: 'Node.js is a runtime environment that allows JavaScript to be run on the server side. It uses an event-driven, non-blocking I/O model for building scalable network applications.' },
    { word: 'Express.js', definition: 'Express.js is a minimal and flexible Node.js web application framework that provides a robust set of features for building web and mobile applications.' },
    { word: 'Django', definition: 'Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design. It simplifies building complex, database-driven websites.' },
    { word: 'Flask', definition: 'Flask is a lightweight Python web framework that provides the essentials to build web applications. It is designed to be simple and easy to extend.' },
    { word: 'Spring Boot', definition: 'Spring Boot is an extension of the Spring framework that simplifies the setup and development of production-ready Spring applications. It aims to reduce boilerplate code and configuration.' },
    { word: 'ASP.NET', definition: 'ASP.NET is a framework for building modern web applications and services with .NET. It supports building dynamic websites and APIs with a focus on performance and scalability.' },
    { word: 'Rust', definition: 'Rust is a systems programming language focused on safety, speed, and concurrency. It is designed to prevent memory-related bugs and is used in performance-critical applications.' },
    { word: 'Kotlin', definition: 'Kotlin is a statically typed programming language that runs on the Java Virtual Machine (JVM). It is designed to be fully interoperable with Java and is used for Android development and backend services.' },
    { word: 'Scala', definition: 'Scala is a high-level programming language that combines object-oriented and functional programming paradigms. It is designed to be concise and is used for scalable systems and data processing.' },
    { word: 'Perl', definition: 'Perl is a high-level, interpreted programming language known for its text-processing capabilities. It is used in web development, system administration, and network programming.' },
    { word: 'Bash/Shell Scripting', definition: 'Bash is a Unix shell and command language used for writing scripts that automate tasks in Unix-like operating systems. Shell scripting involves writing scripts to automate command-line operations.' },
    { word: 'Lua', definition: 'Lua is a lightweight, high-level scripting language designed for embedding in applications. It is known for its simplicity and is often used in game development and embedded systems.' },
    { word: 'Assembly Language', definition: 'Assembly language is a low-level programming language that provides a symbolic representation of a computer’s machine code instructions. It is used for performance-critical applications and systems programming.' },
    { word: 'Clojure', definition: 'Clojure is a modern, functional programming language that runs on the Java Virtual Machine (JVM). It emphasizes immutability and concurrency and is used for concurrent and parallel programming.' },
    { word: 'Groovy', definition: 'Groovy is a dynamic language for the Java platform that combines features of Java with additional scripting capabilities. It is used for scripting, testing, and building web applications.' },
    { word: 'Objective-C', definition: 'Objective-C is an object-oriented programming language used primarily for Apple’s macOS and iOS operating systems. It is known for its dynamic runtime and message-passing capabilities.' },
    { word: 'MATLAB', definition: 'MATLAB is a high-level language and interactive environment for numerical computation, visualization, and programming. It is used extensively in engineering, science, and economics.' },
    { word: 'R', definition: 'R is a language and environment for statistical computing and graphics. It is widely used for data analysis, statistical modeling, and visualization in various fields.' },
    { word: 'F#', definition: 'F# is a functional-first programming language that runs on the .NET framework. It combines functional programming with object-oriented and procedural programming.' },
    { word: 'Dart', definition: 'Dart is a client-optimized programming language developed by Google, designed for building mobile, web, and server applications. It is commonly used with the Flutter framework for mobile development.' },
    { word: 'Julia', definition: 'Julia is a high-level, high-performance programming language designed for technical computing. It is known for its speed and is used in data science, numerical analysis, and machine learning.' },
    { word: 'Haskell', definition: 'Haskell is a purely functional programming language known for its strong type system and lazy evaluation. It is used for research, teaching, and industrial applications requiring advanced functional programming.' },
    { word: 'Solidity', definition: 'Solidity is a high-level, statically-typed programming language designed for developing smart contracts on the Ethereum blockchain.' },
    { word: 'Ethereum', definition: 'Ethereum is a decentralized, open-source blockchain system that features smart contract functionality. It is the platform on which many decentralized applications (dApps) and cryptocurrencies are built.' },
    { word: 'WebAssembly (Wasm)', definition: 'WebAssembly is a binary instruction format designed for efficient execution on the web. It allows code written in languages other than JavaScript to be executed in web browsers at near-native speed.' },
    { word: 'TensorFlow', definition: 'TensorFlow is an open-source machine learning library developed by Google for training and deploying machine learning models, particularly deep learning models.' },
    { word: 'PyTorch', definition: 'PyTorch is an open-source machine learning library developed by Facebook, used for deep learning and artificial intelligence research and production.' },
    { word: 'Keras', definition: 'Keras is an open-source software library that provides a Python interface for neural networks. It acts as an interface for the TensorFlow library.' },
    { word: 'OpenCV', definition: 'OpenCV is an open-source computer vision and machine learning library. It provides tools for image and video processing and is used in applications requiring computer vision.' },
    { word: 'Pandas', definition: 'Pandas is an open-source data analysis and manipulation library for Python. It provides data structures and functions needed to work on structured data seamlessly.' },
    { word: 'NumPy', definition: 'NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions.' },
    { word: 'GraphQL', definition: 'GraphQL is a query language for APIs and a server-side runtime for executing queries by providing a more efficient and flexible alternative to REST.' },
    { word: 'Apache Kafka', definition: 'Apache Kafka is an open-source stream-processing platform developed by LinkedIn. It is used for building real-time data pipelines and streaming applications.' },
    { word: 'Redis', definition: 'Redis is an open-source, in-memory data structure store used as a database, cache, and message broker. It supports various data structures like strings, hashes, lists, and sets.' },
    { word: 'Elasticsearch', definition: 'Elasticsearch is an open-source search and analytics engine used for full-text search, logging, and analyzing large volumes of data.' },
    { word: 'Docker', definition: 'Docker is a platform used for developing, shipping, and running applications inside containers. It enables consistent environments and scalable deployments.' },
    { word: 'Kubernetes', definition: 'Kubernetes is an open-source platform designed for automating the deployment, scaling, and management of containerized applications.' },
    { word: 'AWS (Amazon Web Services)', definition: 'AWS is a comprehensive and widely adopted cloud platform offered by Amazon, providing a range of cloud services including computing power, storage, and databases.' },
    { word: 'Microsoft Azure', definition: 'Microsoft Azure is a cloud computing service created by Microsoft that offers a range of services including virtual machines, databases, and AI tools.' },
    { word: 'Google Cloud Platform (GCP)', definition: 'Google Cloud Platform is a suite of cloud computing services provided by Google, including infrastructure as a service (IaaS), platform as a service (PaaS), and software as a service (SaaS).' },
    { word: 'Serverless Computing', definition: 'Serverless computing allows developers to build and run applications without managing servers. Providers automatically handle the infrastructure, scaling, and maintenance.' },
    { word: 'Microservices Architecture', definition: 'Microservices architecture is a design pattern where an application is composed of loosely coupled, independently deployable services that communicate over a network.' },
    { word: 'DevOps', definition: 'DevOps is a set of practices that combines software development (Dev) and IT operations (Ops) to improve collaboration, automation, and efficiency in software delivery.' },
    { word: 'Continuous Integration / Continuous Deployment (CI/CD)', definition: 'CI/CD refers to the practices of continuously integrating code changes and deploying them to production environments automatically, ensuring rapid and reliable delivery of software.' },
    { word: 'Agile Methodologies', definition: 'Agile methodologies are approaches to software development that emphasize iterative progress, collaboration, and flexibility to adapt to changes quickly.' },
    { word: 'Test-Driven Development (TDD)', definition: 'Test-Driven Development is a software development process where tests are written before the code that needs to be tested, ensuring that the software meets the requirements.' },
    { word: 'Behavior-Driven Development (BDD)', definition: 'Behavior-Driven Development is a software development approach that emphasizes collaboration between developers, testers, and business stakeholders to define and validate the behavior of software.' },
    { word: 'Git', definition: 'Git is a distributed version control system used to track changes in source code during software development. It allows multiple developers to work on a project concurrently.' },
    { word: 'Subversion (SVN)', definition: 'Subversion (SVN) is a centralized version control system used to manage and track changes to files and directories, facilitating collaboration among developers.' },
    { word: 'Mercurial (Hg)', definition: 'Mercurial is a distributed version control system used for managing and tracking changes in source code, offering similar functionality to Git.' },
    { word: 'Jenkins', definition: 'Jenkins is an open-source automation server used for continuous integration and continuous delivery (CI/CD), helping to automate various stages of the software development lifecycle.' },
    { word: 'CircleCI', definition: 'CircleCI is a cloud-based continuous integration and continuous delivery (CI/CD) platform that automates the process of building, testing, and deploying software.' },
    { word: 'Travis CI', definition: 'Travis CI is a continuous integration service used to build and test code changes in GitHub repositories, facilitating automated software testing and deployment.' },
    { word: 'Jira', definition: 'Jira is a project management and issue-tracking tool developed by Atlassian, used for tracking tasks, bugs, and project progress in software development.' },
    { word: 'Confluence', definition: 'Confluence is a collaboration and documentation platform developed by Atlassian, used for creating, sharing, and managing project documentation and team knowledge.' },
    { word: 'Slack (for Development Teams)', definition: 'Slack is a messaging platform designed for team communication and collaboration, providing channels, direct messaging, and integrations with various development tools.' },
    { word: 'Agile Project Management Tools', definition: 'Agile project management tools are software applications that support Agile methodologies, facilitating task tracking, collaboration, and iterative development processes.' },
    { word: 'Scrum', definition: 'Scrum is an Agile framework for managing and completing complex projects through iterative development, with defined roles, events, and artifacts to guide the process.' },
    { word: 'Kanban', definition: 'Kanban is a visual project management methodology that emphasizes continuous delivery, flow efficiency, and incremental improvements using visual boards and cards.' },
    { word: 'Pair Programming', definition: 'Pair programming is a software development technique where two programmers work together at one workstation, with one writing code and the other reviewing and providing guidance.' },
    { word: 'Code Review', definition: 'Code review is the process of evaluating and examining source code by developers other than the author to ensure quality, correctness, and adherence to coding standards.' },
    { word: 'Cryptography', definition: 'Cryptography is the practice of securing communication and data through the use of mathematical algorithms and protocols to prevent unauthorized access and ensure data integrity.' },
    { word: 'Cybersecurity', definition: 'Cybersecurity involves protecting computer systems, networks, and data from digital attacks, theft, and damage through various strategies and technologies.' },
    { word: 'Penetration Testing', definition: 'Penetration testing, or ethical hacking, is the practice of testing a computer system or network for vulnerabilities by simulating attacks to identify and address potential security weaknesses.' },
    { word: 'Web Development', definition: 'Web development is the process of creating and maintaining websites and web applications, involving both front-end (client-side) and back-end (server-side) development tasks.' },
    { word: 'Mobile App Development', definition: 'Mobile app development is the process of creating software applications specifically for mobile devices such as smartphones and tablets, using platforms like Android and iOS.' },
    { word: 'Game Development', definition: 'Game development is the process of designing, creating, and programming video games for various platforms, including consoles, PCs, and mobile devices.' },
    { word: 'Augmented Reality (AR)', definition: 'Augmented Reality (AR) is a technology that overlays digital information onto the real world, enhancing user experiences through interactive and immersive visuals.' },
    { word: 'Virtual Reality (VR)', definition: 'Virtual Reality (VR) is a technology that creates a simulated environment that users can interact with using specialized equipment, providing immersive experiences in a virtual world.' },
    { word: 'Blockchain Development', definition: 'Blockchain development involves creating and implementing blockchain technology, which is a decentralized ledger system used for secure and transparent transactions and data storage.' },
    { word: 'Cryptocurrency', definition: 'Cryptocurrency is a digital or virtual currency that uses cryptography for security and operates independently of a central authority, like Bitcoin and Ethereum.' },
    { word: 'Decentralized Finance (DeFi)', definition: 'Decentralized Finance (DeFi) refers to financial services built on blockchain technology that operate without traditional intermediaries, such as banks or brokers.' },
    { word: 'Artificial Intelligence (AI)', definition: 'Artificial Intelligence (AI) is the simulation of human intelligence in machines designed to think and learn like humans, encompassing areas such as machine learning, natural language processing, and robotics.' },
    { word: 'Machine Learning', definition: 'Machine Learning is a subset of AI that enables systems to learn and improve from experience without being explicitly programmed, using algorithms and statistical models.' },
    { word: 'Natural Language Processing (NLP)', definition: 'Natural Language Processing (NLP) is a field of AI focused on the interaction between computers and human languages, enabling machines to understand, interpret, and generate human language.' },
    { word: 'Computer Vision', definition: 'Computer Vision is a field of AI that enables computers to interpret and understand visual information from the world, such as images and videos, using algorithms and models.' },
    { word: 'Big Data', definition: 'Big Data refers to extremely large datasets that are analyzed computationally to reveal patterns, trends, and associations, particularly related to human behavior and interactions.' },
    { word: 'Data Engineering', definition: 'Data Engineering involves designing and building systems for collecting, storing, and analyzing large volumes of data, ensuring data quality, accessibility, and usability.' },
    { word: 'Data Analytics', definition: 'Data Analytics is the process of examining datasets to draw conclusions and make informed decisions, using statistical and computational techniques to uncover insights.' },
    { word: 'Data Visualization', definition: 'Data Visualization is the graphical representation of information and data, using charts, graphs, and other visual tools to help users understand complex data and make data-driven decisions.' },
    { word: 'Business Intelligence (BI)', definition: 'Business Intelligence (BI) encompasses tools, technologies, and practices for collecting, analyzing, and presenting business data to support decision-making and strategic planning.' },
    { word: 'Internet of Things (IoT)', definition: 'The Internet of Things (IoT) refers to the network of interconnected devices that can collect, share, and act on data, enabling automation and intelligent decision-making in various applications.' },
    { word: 'Embedded Systems', definition: 'Embedded Systems are specialized computing systems designed to perform dedicated functions or tasks within larger systems, often with real-time computing constraints.' },
    { word: 'Quantum Computing', definition: 'Quantum Computing is an area of computing that uses quantum-mechanical phenomena, such as superposition and entanglement, to perform computations that are infeasible for classical computers.' }
];

const isValidInterest = (interestValue: string) => {
    return interests.includes(interestValue);
}

export {
    interests,
    isValidInterest,
    detailedInterests
};